steps:
  - name: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile",
           "--context=dir://src/adservice",
           "--destination=gcr.io/callidus-open-source/microservice-demo/adservice:latest"]
