steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/adservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/adservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/cartservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/cartservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/checkoutservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/checkoutservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/currencyservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/currencyservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/emailservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/emailservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/frontend'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/frontend:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/loadgenerator'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/loadgenerator:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/paymentservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/paymentservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/productcatalogservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/productcatalogservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/recommendationservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/recommendationservice:release-$COMMIT_SHA-$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir:  'src/shippingservice'
    args: ['build', '-t', 'gcr.io/callidus-open-source/microservice-demo/shippingservice:release-$COMMIT_SHA-$BUILD_ID', '.']

images: ['gcr.io/callidus-open-source/microservice-demo/adservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/cartservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/checkoutservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/currencyservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/emailservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/frontend:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/loadgenerator:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/paymentservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/productcatalogservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/recommendationservice:release-$COMMIT_SHA-$BUILD_ID',
         'gcr.io/callidus-open-source/microservice-demo/shippingservice:release-$COMMIT_SHA-$BUILD_ID']

timeout: 4000s   
options:
  diskSizeGb: 300
  machineType: "N1_HIGHCPU_32"
